question_data = [{"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also "
                              "known to be a descendant of the Tyrannosaurus Rex.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The cover of The Beatles album 'Abbey Road' featured a Volkswagen Beetle in the "
                              "background.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "There are no roads in/out of Juneau, Alaska.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In 'Super Mario 64', collecting 100 coins on a level will give you a 1-UP.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Board Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In the game 'Racko' you may pick up ANY card from the discard pile.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The 'Berenstein Bears' is the correct spelling of the educational children's book "
                              "series' name.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "'I disapprove of what you say, but I will defend to the death your right to say it' is "
                              "a quote from French philosopher Voltaire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "There are 6 legendary cards in 'Clash Royale'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Brezhnev was the 5th leader of the USSR.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "medium",
                  "question": "The animated film 'Spirited Away' won the Academy Award for Best Animated Feature at "
                              "the 75th Academy Awards in 2003.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of "
                              "urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Tony Hawk's Pro Skater was released in 1999.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Bill Cipher in the show 'Gravity Falls' is the good guy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The average woman is 5 inches/13 centimeters shorter than the average man.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "hard",
                  "question": "In Undertale, having a 'Fun Value' set to 56-57 will play the 'Wrong Number Song Call'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "hard",
                  "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be "
                              "appeased monthly with the sacrifice of a virgin girl.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A flock of crows is known as a homicide.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In the game 'Subnautica', a 'Cave Crawler' will attack you.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed "
                              "Darth Vader.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border wall "
                              "between the United States and Mexico.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Windows ME operating system was released in the year 2000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Brandon Routh plays the titular character in the movie 'John Wick'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Mortal Kombat was almost based on Jean-Claude Van Damme movie.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "'Minions' was released on the June 10th, 2015.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy", "question": "Watch_Dogs 2 is a prequel.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In 'Star Trek', Klingons are aliens.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "medium",
                  "question": "The Roman god 'Jupiter' was first known as 'Zeus' to the Greeks.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "An average human can go two weeks without water.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Art", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Board Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "'Rich Uncle Pennybags' from the board game 'Monopoly' wears a monocle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Actor Tommy Chong served prison time.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "Finnish Lapphund dogs were used for herding reindeer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 "
                              "inside swimming pools and drinking water.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In 'Star Trek: The Next Generation', Data is the only android in existence.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "hard",
                  "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural "
                              "area known as  'the Zone'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Rhode Island is actually located on the US mainland, despite its name.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Rabbits can see what's behind themselves without turning their heads.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Donald Duck played the role of Bob Cratchit in Disney's 1983 adaptation of A Christmas "
                              "Carol.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Vietnam's national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the "
                              "final chapter of the game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "A Boolean value of '0' represents which of these words?",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Is Tartu the capital of Estonia?",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
